server:
  #  端口
  port: 8080


spring:
  profiles:
    #    引用配置文件
    active: dev

mybatis:
  #  mapper 文件扫描配置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # mybatis 配置
  configuration:
    #   驼峰自动映射
    map-underscore-to-camel-case: true


