spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/super-daily-attendance?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      max-active: 8 #最大连接池数量
      minIdle: 1 #最小连接池数量
      initial-size: 5
      max-wait: 10000
      keep-alive: true
      min-evictable-idle-time-millis: 60000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      validation-query-timeout: 15000
      validation-query: select 'x'
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
      webStatFilter: #WebStatFilter用于采集web-jdbc关联监控的数据。
        enabled: true
      statViewServlet: #提供监控信息展示的html页面 与 提供监控信息的JSON API
        enabled: true
        # 设置白名单，不填则允许所有访问， 填入的值为IP地址
        allow: #允许访问例子：128.242.127.1/24  24表示前面24位时子网掩码， 比对的时候比较前24位是否相同。但是目前不支持IPV6
        deny: #不允许访问的地址，该配置优于allow，如果在该列表配置过，那么就算在allow配置也会不允许访问
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: druid
        login-password: 123456



